In [54]:
import numpy as np
import pandas as pd
import datetime as dt
from datetime import date,timedelta
np.random.seed(42)

In [55]:
data=pd.read_csv('merged_ecommerce_data.csv')

In [56]:
data.head()

,customer_id,signup_date,age,gender,order_date,amount,currency,status,device,country,event
0,C4160,2023-10-17,30.0,0.0,2022-02-22,99.975488,USD,completed,mobile,US,click
1,C4160,2023-10-17,30.0,0.0,2023-08-12,-264.571496,USD,completed,desktop,US,click
2,C2075,2022-01-22,28.0,0.0,2023-10-15,220.348791,USD,refunded,mobile,US,purchase
3,C285,2023-02-21,28.0,1.0,2023-03-10,-92.077224,USD,completed,mobile,UK,view
4,C4934,2022-05-13,30.0,0.0,2023-04-26,-177.631072,USD,refunded,desktop,US,purchase

In [57]:
data_sub=data.copy()

In [58]:
data_sub.duplicated().sum()

np.int64(0)

In [59]:
data_sub['currency'].value_counts()
data_sub['device'].value_counts()
data_sub['customer_id'].value_counts()[:10]

customer_id
C2064    147
C5540    147
C4229    147
C3689    147
C4355    147
C762     108
C3176    108
C4523    108
C1130    108
C3719    108
Name: count, dtype: int64

In [60]:
data_sub.head(10)

,customer_id,signup_date,age,gender,order_date,amount,currency,status,device,country,event
0,C4160,2023-10-17,30.0,0.0,2022-02-22,99.975488,USD,completed,mobile,US,click
1,C4160,2023-10-17,30.0,0.0,2023-08-12,-264.571496,USD,completed,desktop,US,click
2,C2075,2022-01-22,28.0,0.0,2023-10-15,220.348791,USD,refunded,mobile,US,purchase
3,C285,2023-02-21,28.0,1.0,2023-03-10,-92.077224,USD,completed,mobile,UK,view
4,C4934,2022-05-13,30.0,0.0,2023-04-26,-177.631072,USD,refunded,desktop,US,purchase
5,C4927,2022-02-18,25.0,0.0,2023-04-09,-487.638339,USD,refunded,desktop,US,click
6,C4927,2022-02-18,25.0,0.0,2023-04-09,-487.638339,USD,refunded,desktop,US,purchase
7,C4927,2022-02-18,25.0,0.0,2023-09-10,161.252214,USD,completed,mobile,UK,click
8,C4927,2022-02-18,25.0,0.0,2023-09-10,161.252214,USD,completed,mobile,UK,purchase
9,C1188,2022-03-06,28.0,1.0,2022-03-04,34.760136,USD,completed,desktop,US,click

In [61]:
data_sub.shape

(39753, 11)

In [62]:
data_sub.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 39753 entries, 0 to 39752
Data columns (total 11 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   customer_id  39753 non-null  object
 1   signup_date  39753 non-null  object
 2   age          39753 non-null  float64
 3   gender       39753 non-null  float64
 4   order_date   39753 non-null  object
 5   amount       39753 non-null  float64
 6   currency     39753 non-null  object
 7   status       39753 non-null  object
 8   device       39753 non-null  object
 9   country      39753 non-null  object
 10  event        39753 non-null  object
dtypes: float64(3), object(8)
memory usage: 3.3+ MB

In [63]:
data_sub['signup_date']=pd.to_datetime(data_sub['signup_date'])
data_sub['order_date']=pd.to_datetime(data_sub['order_date'])

In [64]:
data_sub.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 39753 entries, 0 to 39752
Data columns (total 11 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   customer_id  39753 non-null  object
 1   signup_date  39753 non-null  datetime64[ns]
 2   age          39753 non-null  float64
 3   gender       39753 non-null  float64
 4   order_date   39753 non-null  datetime64[ns]
 5   amount       39753 non-null  float64
 6   currency     39753 non-null  object
 7   status       39753 non-null  object
 8   device       39753 non-null  object
 9   country      39753 non-null  object
 10  event        39753 non-null  object
dtypes: datetime64[ns](2), float64(3), object(6)
memory usage: 3.3+ MB

In [65]:
data_sub=data_sub.drop(columns=['currency'])

In [66]:
data_sub.head()

,customer_id,signup_date,age,gender,order_date,amount,status,device,country,event
0,C4160,2023-10-17,30.0,0.0,2022-02-22,99.975488,completed,mobile,US,click
1,C4160,2023-10-17,30.0,0.0,2023-08-12,-264.571496,completed,desktop,US,click
2,C2075,2022-01-22,28.0,0.0,2023-10-15,220.348791,refunded,mobile,US,purchase
3,C285,2023-02-21,28.0,1.0,2023-03-10,-92.077224,completed,mobile,UK,view
4,C4934,2022-05-13,30.0,0.0,2023-04-26,-177.631072,refunded,desktop,US,purchase

**FEATURE ENGINEERING**

In [67]:
invalid = (data_sub['order_date'] < data_sub['signup_date']).sum()
total = len(data_sub)

print(f"{invalid} rows ({invalid/total:.2%}) have order_date before signup_date")

20874 rows (52.51%) have order_date before signup_date

**Working on signup_dates and order_date**

In [68]:
new_order_dates=[]
current_signup_dates=data_sub['signup_date']

for i in current_signup_dates:
    new_date= i + timedelta(days=np.random.randint(1,365*2))
    new_order_dates.append(new_date)

data_sub['order_date']=new_order_dates

In [69]:
data_sub.head()

,customer_id,signup_date,age,gender,order_date,amount,status,device,country,event
0,C4160,2023-10-17,30.0,0.0,2024-01-28,99.975488,completed,mobile,US,click
1,C4160,2023-10-17,30.0,0.0,2024-12-26,-264.571496,completed,desktop,US,click
2,C2075,2022-01-22,28.0,0.0,2022-10-20,220.348791,refunded,mobile,US,purchase
3,C285,2023-02-21,28.0,1.0,2023-06-08,-92.077224,completed,mobile,UK,view
4,C4934,2022-05-13,30.0,0.0,2022-07-24,-177.631072,refunded,desktop,US,purchase

In [71]:
data_sub[data_sub['order_date'].duplicated(keep=False)]

,customer_id,signup_date,age,gender,order_date,amount,status,device,country,event,signup_yr,signup_month,signup_day,order_yr,order_month,order_day
0,C4160,2023-10-17,30.0,0.0,2024-01-28,99.975488,completed,mobile,US,click,2023,10,17,2024,1,28
1,C4160,2023-10-17,30.0,0.0,2024-12-26,-264.571496,completed,desktop,US,click,2023,10,17,2024,12,26
2,C2075,2022-01-22,28.0,0.0,2022-10-20,220.348791,refunded,mobile,US,purchase,2022,1,22,2022,10,20
3,C285,2023-02-21,28.0,1.0,2023-06-08,-92.077224,completed,mobile,UK,view,2023,2,21,2023,6,8
4,C4934,2022-05-13,30.0,0.0,2022-07-24,-177.631072,refunded,desktop,US,purchase,2022,5,13,2022,7,24
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
39748,C4499,2022-12-28,25.0,0.0,2024-08-30,-103.288509,completed,desktop,UK,purchase,2022,12,28,2024,8,30
39749,C4499,2022-12-28,25.0,0.0,2024-10-30,-103.288509,completed,desktop,UK,view,2022,12,28,2024,10,30
39750,C4499,2022-12-28,25.0,0.0,2024-10-17,-118.139886,completed,mobile,US,click,2022,12,28,2024,10,17
39751,C4499,2022-12-28,25.0,0.0,2023-12-22,-118.139886,completed,mobile,US,purchase,2022,12,28,2023,12,22
39752,C4499,2022-12-28,25.0,0.0,2024-09-15,-118.139886,completed,mobile,US,view,2022,12,28,2024,9,15

**check if some customer_ids have different signup_dates**

In [72]:
data_sub['customer_id'].duplicated().sum()

np.int64(35496)

In [73]:
data_sub.loc[data_sub['customer_id'].duplicated(keep=False)].sort_values(by='customer_id')

,customer_id,signup_date,age,gender,order_date,amount,status,device,country,event,signup_yr,signup_month,signup_day,order_yr,order_month,order_day
3712,C1002,2022-04-13,25.0,0.0,2022-12-05,-251.416107,refunded,desktop,US,purchase,2022,4,13,2022,12,5
3713,C1002,2022-04-13,25.0,0.0,2023-07-12,-3.000027,completed,desktop,UK,purchase,2022,4,13,2023,7,12
23696,C1002,2022-08-12,25.0,1.0,2024-05-24,-3.000027,completed,desktop,UK,purchase,2022,8,12,2024,5,24
23695,C1002,2022-08-12,25.0,1.0,2024-02-23,-251.416107,refunded,desktop,US,purchase,2022,8,12,2024,2,23
34667,C1005,2022-01-02,28.0,1.0,2023-11-15,-351.899512,completed,mobile,US,click,2022,1,2,2023,11,15
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3073,C999,2023-08-19,28.0,0.0,2024-01-08,305.335477,refunded,desktop,US,click,2023,8,19,2024,1,8
3074,C999,2023-08-19,28.0,0.0,2025-04-22,305.335477,refunded,desktop,US,view,2023,8,19,2025,4,22
3075,C999,2023-08-19,28.0,0.0,2025-01-01,-38.847425,completed,desktop,UK,click,2023,8,19,2025,1,1
14542,C999,2023-05-13,25.0,1.0,2024-05-01,56.579949,refunded,mobile,US,click,2023,5,13,2024,5,1
3078,C999,2023-08-19,28.0,0.0,2025-06-08,56.579949,refunded,mobile,US,view,2023,8,19,2025,6,8

In [75]:
# this loop took min. 60mins to execute results....

#customer_ids=[]
#random_values= np.random.randint(1,len(data_sub) + 1,size=len(data_sub))

#for k in data_sub['customer_id']:
 #   if [i for i in data_sub['signup_date']]== [j for j in data_sub['signup_date']]:
  #      k=k
   #     customer_ids.append(k)
    #else:
     #   new_ids=[f'C{m}' for m in random_values]
      #  if new_ids!= k:
       #     customer_ids.append(new_ids)

In [88]:
data_sub['customer_id']=customer_ids

In [89]:
data_sub['signup_yr']=data_sub['signup_date'].dt.year
data_sub['signup_month']=data_sub['signup_date'].dt.month
data_sub['signup_day']=data_sub['signup_date'].dt.day

data_sub['order_yr']=data_sub['order_date'].dt.year
data_sub['order_month']=data_sub['order_date'].dt.month
data_sub['order_day']=data_sub['order_date'].dt.day

**The negative amounts having completed status and positive amounts having refunded status and vice versa**

In [90]:
negative_completed=data_sub[data_sub['amount'] < 0] [data_sub['status'] == 'completed']

negative_completed

/tmp/ipykernel_4626/379698938.py:1: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  negative_completed=data_sub[data_sub['amount'] < 0] [data_sub['status'] == 'completed']

,customer_id,signup_date,age,gender,order_date,amount,status,device,country,event,signup_yr,signup_month,signup_day,order_yr,order_month,order_day
1,C4160,2023-10-17,30.0,0.0,2024-12-26,-264.571496,completed,desktop,US,click,2023,10,17,2024,12,26
3,C285,2023-02-21,28.0,1.0,2023-06-08,-92.077224,completed,mobile,UK,view,2023,2,21,2023,6,8
18,C1188,2022-03-06,28.0,1.0,2023-12-28,-34.160684,completed,mobile,US,click,2022,3,6,2023,12,28
19,C1188,2022-03-06,28.0,1.0,2023-01-09,-34.160684,completed,mobile,US,purchase,2022,3,6,2023,1,9
20,C1188,2022-03-06,28.0,1.0,2023-02-13,-34.160684,completed,mobile,US,view,2022,3,6,2023,2,13
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
39748,C4499,2022-12-28,25.0,0.0,2024-08-30,-103.288509,completed,desktop,UK,purchase,2022,12,28,2024,8,30
39749,C4499,2022-12-28,25.0,0.0,2024-10-30,-103.288509,completed,desktop,UK,view,2022,12,28,2024,10,30
39750,C4499,2022-12-28,25.0,0.0,2024-10-17,-118.139886,completed,mobile,US,click,2022,12,28,2024,10,17
39751,C4499,2022-12-28,25.0,0.0,2023-12-22,-118.139886,completed,mobile,US,purchase,2022,12,28,2023,12,22
39752,C4499,2022-12-28,25.0,0.0,2024-09-15,-118.139886,completed,mobile,US,view,2022,12,28,2024,9,15

In [91]:
negative_refunded=data_sub[data_sub['amount']< 0][data_sub['status']=='refunded']
negative_refunded

/tmp/ipykernel_4626/693956655.py:1: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  negative_refunded=data_sub[data_sub['amount']< 0][data_sub['status']=='refunded']

,customer_id,signup_date,age,gender,order_date,amount,status,device,country,event,signup_yr,signup_month,signup_day,order_yr,order_month,order_day
4,C4934,2022-05-13,30.0,0.0,2022-07-24,-177.631072,refunded,desktop,US,purchase,2022,5,13,2022,7,24
5,C4927,2022-02-18,25.0,0.0,2024-01-20,-487.638339,refunded,desktop,US,click,2022,2,18,2024,1,20
6,C4927,2022-02-18,25.0,0.0,2022-03-11,-487.638339,refunded,desktop,US,purchase,2022,2,18,2022,3,11
21,C3970,2022-04-14,30.0,0.0,2023-08-19,-0.948647,refunded,desktop,US,purchase,2022,4,14,2023,8,19
22,C3970,2022-04-14,30.0,0.0,2023-06-02,-0.948647,refunded,desktop,US,view,2022,4,14,2023,6,2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
39735,C272,2023-10-12,30.0,1.0,2025-03-09,-141.459131,refunded,mobile,US,view,2023,10,12,2025,3,9
39736,C272,2023-10-12,30.0,1.0,2025-05-14,-290.975420,refunded,mobile,US,purchase,2023,10,12,2025,5,14
39737,C272,2023-10-12,30.0,1.0,2024-05-09,-290.975420,refunded,mobile,US,view,2023,10,12,2024,5,9
39742,C2031,2022-08-23,28.0,0.0,2024-01-17,-111.676605,refunded,mobile,US,click,2022,8,23,2024,1,17
39743,C2031,2022-08-23,28.0,0.0,2023-05-28,-111.676605,refunded,mobile,US,purchase,2022,8,23,2023,5,28

In [92]:
positive_completed=data_sub[data_sub['amount'] > 0] [data_sub['status']=='completed'] 
positive_completed

/tmp/ipykernel_4626/3984848566.py:1: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  positive_completed=data_sub[data_sub['amount'] > 0] [data_sub['status']=='completed']

,customer_id,signup_date,age,gender,order_date,amount,status,device,country,event,signup_yr,signup_month,signup_day,order_yr,order_month,order_day
0,C4160,2023-10-17,30.0,0.0,2024-01-28,99.975488,completed,mobile,US,click,2023,10,17,2024,1,28
7,C4927,2022-02-18,25.0,0.0,2023-10-26,161.252214,completed,mobile,UK,click,2022,2,18,2023,10,26
8,C4927,2022-02-18,25.0,0.0,2022-06-20,161.252214,completed,mobile,UK,purchase,2022,2,18,2022,6,20
9,C1188,2022-03-06,28.0,1.0,2023-06-16,34.760136,completed,desktop,US,click,2022,3,6,2023,6,16
10,C1188,2022-03-06,28.0,1.0,2022-10-07,34.760136,completed,desktop,US,purchase,2022,3,6,2022,10,7
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
39740,C2031,2022-08-23,28.0,0.0,2023-03-29,77.538555,completed,desktop,US,click,2022,8,23,2023,3,29
39741,C2031,2022-08-23,28.0,0.0,2023-11-22,77.538555,completed,desktop,US,purchase,2022,8,23,2023,11,22
39744,C4499,2022-12-28,25.0,0.0,2023-06-26,3.532230,completed,desktop,US,click,2022,12,28,2023,6,26
39745,C4499,2022-12-28,25.0,0.0,2024-05-28,3.532230,completed,desktop,US,purchase,2022,12,28,2024,5,28
39746,C4499,2022-12-28,25.0,0.0,2023-05-07,3.532230,completed,desktop,US,view,2022,12,28,2023,5,7

In [93]:
positive_refunded= data_sub[data_sub['amount']>0][data_sub['status']=='refunded']
positive_refunded

/tmp/ipykernel_4626/3140317641.py:1: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  positive_refunded= data_sub[data_sub['amount']>0][data_sub['status']=='refunded']

,customer_id,signup_date,age,gender,order_date,amount,status,device,country,event,signup_yr,signup_month,signup_day,order_yr,order_month,order_day
2,C2075,2022-01-22,28.0,0.0,2022-10-20,220.348791,refunded,mobile,US,purchase,2022,1,22,2022,10,20
12,C1188,2022-03-06,28.0,1.0,2023-06-08,107.816491,refunded,mobile,US,click,2022,3,6,2023,6,8
13,C1188,2022-03-06,28.0,1.0,2022-06-02,107.816491,refunded,mobile,US,purchase,2022,3,6,2022,6,2
14,C1188,2022-03-06,28.0,1.0,2023-03-14,107.816491,refunded,mobile,US,view,2022,3,6,2023,3,14
37,C4320,2023-05-11,30.0,0.0,2025-04-10,77.693704,refunded,desktop,US,click,2023,5,11,2025,4,10
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
39672,C5191,2023-11-08,28.0,1.0,2025-01-07,84.448891,refunded,desktop,UK,view,2023,11,8,2025,1,7
39709,C1103,2022-06-28,30.0,0.0,2022-09-28,115.942053,refunded,mobile,UK,click,2022,6,28,2022,9,28
39710,C1103,2022-06-28,30.0,0.0,2024-02-26,115.942053,refunded,mobile,UK,purchase,2022,6,28,2024,2,26
39732,C272,2023-10-12,30.0,1.0,2023-11-30,108.852801,refunded,desktop,US,purchase,2023,10,12,2023,11,30
39733,C272,2023-10-12,30.0,1.0,2024-05-06,108.852801,refunded,desktop,US,view,2023,10,12,2024,5,6

In [94]:
(negative_refunded.shape[0] / len(data_sub) ) * 100

17.311900988604634

In [95]:
(negative_completed.shape[0] / len(data_sub) ) * 100

33.318240132820165

In [96]:
(positive_completed.shape[0] / len(data_sub) ) * 100

31.962367620053833

In [97]:
(positive_refunded.shape[0] / len(data_sub) ) * 100

17.407491258521368

**Based on findings above;Customers who have negative amounts should have refunded status else completed**

In [98]:
data_sub['status'].value_counts()

status
completed    25951
refunded     13802
Name: count, dtype: int64

In [99]:
amounts=data_sub['amount']
status=data_sub['status']

status_redone=[]

for i in amounts:
    if i < 0:
        status= 'refunded'
        status_redone.append(status)
    else:
        status='completed'
        status_redone.append(status)

In [100]:
data_sub['status']=status_redone
data_sub['status'].value_counts()

status
refunded     20127
completed    19626
Name: count, dtype: int64

In [101]:
data_sub.head()

,customer_id,signup_date,age,gender,order_date,amount,status,device,country,event,signup_yr,signup_month,signup_day,order_yr,order_month,order_day
0,C4160,2023-10-17,30.0,0.0,2024-01-28,99.975488,completed,mobile,US,click,2023,10,17,2024,1,28
1,C4160,2023-10-17,30.0,0.0,2024-12-26,-264.571496,refunded,desktop,US,click,2023,10,17,2024,12,26
2,C2075,2022-01-22,28.0,0.0,2022-10-20,220.348791,completed,mobile,US,purchase,2022,1,22,2022,10,20
3,C285,2023-02-21,28.0,1.0,2023-06-08,-92.077224,refunded,mobile,UK,view,2023,2,21,2023,6,8
4,C4934,2022-05-13,30.0,0.0,2022-07-24,-177.631072,refunded,desktop,US,purchase,2022,5,13,2022,7,24

In [109]:
data_sub.head()
modified_merged_data=data_sub.drop(columns=['signup_yr','signup_month','signup_day','order_yr','order_month','order_day'])

In [110]:
data.head()

,customer_id,signup_date,age,gender,order_date,amount,currency,status,device,country,event
0,C4160,2023-10-17,30.0,0.0,2022-02-22,99.975488,USD,completed,mobile,US,click
1,C4160,2023-10-17,30.0,0.0,2023-08-12,-264.571496,USD,completed,desktop,US,click
2,C2075,2022-01-22,28.0,0.0,2023-10-15,220.348791,USD,refunded,mobile,US,purchase
3,C285,2023-02-21,28.0,1.0,2023-03-10,-92.077224,USD,completed,mobile,UK,view
4,C4934,2022-05-13,30.0,0.0,2023-04-26,-177.631072,USD,refunded,desktop,US,purchase

In [111]:
modified_merged_data['currency']=data['currency']

In [112]:
modified_merged_data.head()

,customer_id,signup_date,age,gender,order_date,amount,status,device,country,event,currency
0,C4160,2023-10-17,30.0,0.0,2024-01-28,99.975488,completed,mobile,US,click,USD
1,C4160,2023-10-17,30.0,0.0,2024-12-26,-264.571496,refunded,desktop,US,click,USD
2,C2075,2022-01-22,28.0,0.0,2022-10-20,220.348791,completed,mobile,US,purchase,USD
3,C285,2023-02-21,28.0,1.0,2023-06-08,-92.077224,refunded,mobile,UK,view,USD
4,C4934,2022-05-13,30.0,0.0,2022-07-24,-177.631072,refunded,desktop,US,purchase,USD

In [113]:
#modified_merged_data.to_csv('modified_merged_ecommerce_data.csv')