In [111]:
import numpy as np
import pandas as pd

np.random.seed(42)

In [112]:
customer_data=pd.read_csv('customers.csv')

In [113]:
customer_data.head()

  customer_id       email signup_date   age gender
0       C_100  a@mail.com  17/10/2023  30.0      F
1        C101  a@mail.com  2022/01/22   NaN    NaN
2       C_100  b@mail.com  21/02/2023   NaN      M
3        C100     unknown  13/05/2022  30.0      F
4       C_100     unknown  18/02/2022  25.0    NaN

In [114]:
customer_data_sub=customer_data.copy()

In [115]:
#there is inconsistency in the signup_date column
customer_data_sub['signup_date']=pd.to_datetime(customer_data_sub['signup_date'],format='mixed')

In [116]:
customer_data_sub.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8000 entries, 0 to 7999
Data columns (total 5 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   customer_id  8000 non-null   object
 1   email        8000 non-null   object
 2   signup_date  8000 non-null   datetime64[ns]
 3   age          5378 non-null   float64
 4   gender       5288 non-null   object
dtypes: datetime64[ns](1), float64(1), object(3)
memory usage: 312.6+ KB

In [117]:
missing_cols=customer_data_sub.isnull().any(axis=1).sum()
missing_rows=customer_data_sub.isnull().any(axis=0).sum()
missing_cols,missing_rows

(np.int64(4416), np.int64(2))

In [118]:
customer_data_sub['age'].describe()

count    5378.000000
mean       27.505578
std         2.500226
min        25.000000
25%        25.000000
50%        30.000000
75%        30.000000
max        30.000000
Name: age, dtype: float64

In [119]:
#filling nan in the age column with the distribution of age in the data
customer_data_sub['age']=customer_data['age'].fillna( np.random.randint(customer_data_sub['age'].min(), customer_data_sub['age'].max() ) )

In [120]:
customer_data_sub['age'].describe()

count    8000.000000
mean       27.667625
std         2.062991
min        25.000000
25%        25.000000
50%        28.000000
75%        30.000000
max        30.000000
Name: age, dtype: float64

In [121]:
customer_data_sub['gender'].describe()

count     5288
unique       2
top          M
freq      2674
Name: gender, dtype: object

In [122]:
customer_data_sub['gender'].value_counts()

gender
M    2674
F    2614
Name: count, dtype: int64

In [123]:
gender_encoding={'M':1, 'F':0}

In [124]:
customer_data_sub['gender']=customer_data_sub['gender'].map(gender_encoding)

In [125]:
customer_data_sub['gender'].value_counts()

gender
1.0    2674
0.0    2614
Name: count, dtype: int64

In [126]:
# fill nan of gender with either 1 or 0;  using random_distribution
customer_data_sub['gender']=customer_data_sub['gender'].fillna(pd.Series(np.random.randint(0,2,size=len(customer_data_sub))))

In [127]:
customer_data_sub['gender'].value_counts()

gender
1.0    4028
0.0    3972
Name: count, dtype: int64

In [128]:
customer_data_sub['customer_id'].value_counts()

customer_id
C100     2700
C_100    2667
C101     2633
Name: count, dtype: int64

In [129]:
customer_data_sub['email'].value_counts()

email
b@mail.com    2727
a@mail.com    2673
unknown       2600
Name: count, dtype: int64

In [130]:
customer_data_sub.head()

  customer_id       email signup_date   age  gender
0       C_100  a@mail.com  2023-10-17  30.0     0.0
1        C101  a@mail.com  2022-01-22  28.0     0.0
2       C_100  b@mail.com  2023-02-21  28.0     1.0
3        C100     unknown  2022-05-13  30.0     0.0
4       C_100     unknown  2022-02-18  25.0     0.0

In [131]:
# dropping nan for in the data;
customer_data_sub=customer_data_sub.dropna().reset_index()
customer_data_sub=customer_data_sub.drop(columns=['index'])

In [132]:
customer_data_sub.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8000 entries, 0 to 7999
Data columns (total 5 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   customer_id  8000 non-null   object
 1   email        8000 non-null   object
 2   signup_date  8000 non-null   datetime64[ns]
 3   age          8000 non-null   float64
 4   gender       8000 non-null   float64
dtypes: datetime64[ns](1), float64(2), object(2)
memory usage: 312.6+ KB

In [133]:
customer_data_sub.head()

  customer_id       email signup_date   age  gender
0       C_100  a@mail.com  2023-10-17  30.0     0.0
1        C101  a@mail.com  2022-01-22  28.0     0.0
2       C_100  b@mail.com  2023-02-21  28.0     1.0
3        C100     unknown  2022-05-13  30.0     0.0
4       C_100     unknown  2022-02-18  25.0     0.0

In [134]:
customer_data_sub['customer_id'].value_counts()

customer_id
C100     2700
C_100    2667
C101     2633
Name: count, dtype: int64

In [135]:
# changing the customer_id distribution since there is few unique entities along the dataset(C100,C_100,C101) which doesn't feel natural...
random_values=np.random.randint(1,(0.7 * len(customer_data_sub)),size=len(customer_data_sub))    
formatted_values=[f'C{i}'for i in random_values]

In [136]:
# replacing existing values of customer_ids with new formatted_values
customer_data_sub['customer_id']=formatted_values

In [137]:
customer_data_sub.head()

  customer_id       email signup_date   age  gender
0       C4160  a@mail.com  2023-10-17  30.0     0.0
1       C2075  a@mail.com  2022-01-22  28.0     0.0
2        C285  b@mail.com  2023-02-21  28.0     1.0
3       C4934     unknown  2022-05-13  30.0     0.0
4       C4927     unknown  2022-02-18  25.0     0.0

In [139]:
# removing duplicates since they are there!
customer_data_sub=customer_data_sub.drop_duplicates()

In [140]:
customer_data_sub.duplicated().sum()

np.int64(0)

**Now cleaning the Orders Dataset**

In [141]:
orders_data=pd.read_csv('orders.csv')

In [142]:
orders_data.head()

,order_id,customer_id,order_date,amount,currency,status,device,country
0,0,C100,2023/08/12,-264.571496,usd,completed,desktop,US
1,1,C100,2023-10-15,220.348791,USD,refunded,mobile,US
2,2,C100,2023/03/10,-92.077224,usd,completed,mobile,UK
3,3,C_100,2023-04-26,-177.631072,USD,refunded,desktop,usa
4,4,C_100,2023-09-10,161.252214,usd,completed,mobile,UK

In [143]:
order_data_sub=orders_data.copy()

In [144]:
#there is inconsistency un the order_date column
order_data_sub['order_date']=pd.to_datetime(order_data_sub['order_date'],format='mixed')

In [145]:
order_data_sub.head()

,order_id,customer_id,order_date,amount,currency,status,device,country
0,0,C100,2023-08-12,-264.571496,usd,completed,desktop,US
1,1,C100,2023-10-15,220.348791,USD,refunded,mobile,US
2,2,C100,2023-03-10,-92.077224,usd,completed,mobile,UK
3,3,C_100,2023-04-26,-177.631072,USD,refunded,desktop,usa
4,4,C_100,2023-09-10,161.252214,usd,completed,mobile,UK

In [146]:
# there is inconsistency in currency column --str
order_data_sub['currency']=order_data_sub['currency'].str.upper()

In [147]:
order_data_sub.head()

,order_id,customer_id,order_date,amount,currency,status,device,country
0,0,C100,2023-08-12,-264.571496,USD,completed,desktop,US
1,1,C100,2023-10-15,220.348791,USD,refunded,mobile,US
2,2,C100,2023-03-10,-92.077224,USD,completed,mobile,UK
3,3,C_100,2023-04-26,-177.631072,USD,refunded,desktop,usa
4,4,C_100,2023-09-10,161.252214,USD,completed,mobile,UK

In [148]:
order_data_sub['status'].value_counts()

status
refunded     2726
Completed    2639
completed    2635
Name: count, dtype: int64

In [149]:
# there is inconsistence in the status column -- completed and Completed

order_data_sub['status']=order_data_sub['status'].str.lower()

In [150]:
order_data_sub['status'].value_counts()

status
completed    5274
refunded     2726
Name: count, dtype: int64

In [151]:
order_data_sub.head()

,order_id,customer_id,order_date,amount,currency,status,device,country
0,0,C100,2023-08-12,-264.571496,USD,completed,desktop,US
1,1,C100,2023-10-15,220.348791,USD,refunded,mobile,US
2,2,C100,2023-03-10,-92.077224,USD,completed,mobile,UK
3,3,C_100,2023-04-26,-177.631072,USD,refunded,desktop,usa
4,4,C_100,2023-09-10,161.252214,USD,completed,mobile,UK

In [152]:
order_data_sub['device'].value_counts()

device
mobile     4072
desktop    3928
Name: count, dtype: int64

In [153]:
#there is inconsistency in country column: us,usa --same thing...
order_data_sub['country'].value_counts()

country
UK     2718
usa    2694
US     2588
Name: count, dtype: int64

In [154]:
order_data_sub['country']=np.where(order_data_sub['country'] == 'usa','US',order_data_sub['country'])

In [155]:
order_data_sub.head()

,order_id,customer_id,order_date,amount,currency,status,device,country
0,0,C100,2023-08-12,-264.571496,USD,completed,desktop,US
1,1,C100,2023-10-15,220.348791,USD,refunded,mobile,US
2,2,C100,2023-03-10,-92.077224,USD,completed,mobile,UK
3,3,C_100,2023-04-26,-177.631072,USD,refunded,desktop,US
4,4,C_100,2023-09-10,161.252214,USD,completed,mobile,UK

In [156]:
order_data_sub.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8000 entries, 0 to 7999
Data columns (total 8 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   order_id     8000 non-null   int64
 1   customer_id  5352 non-null   object
 2   order_date   8000 non-null   datetime64[ns]
 3   amount       8000 non-null   float64
 4   currency     8000 non-null   object
 5   status       8000 non-null   object
 6   device       8000 non-null   object
 7   country      8000 non-null   object
dtypes: datetime64[ns](1), float64(1), int64(1), object(5)
memory usage: 500.1+ KB

In [157]:
orders_col_missing=order_data_sub.isnull().any(axis=1).sum()
orders_rows_missing=order_data_sub.isnull().any(axis=0).sum()
orders_col_missing,orders_rows_missing

(np.int64(2648), np.int64(1))

In [158]:
order_data_sub['customer_id'].value_counts()

customer_id
C100     2745
C_100    2607
Name: count, dtype: int64

In [159]:
random_values_orders=np.random.randint(1,(0.7 * len(order_data_sub)),size=len(order_data_sub))    
formatted_values_orders=[f'C{i}'for i in random_values]

In [160]:
order_data_sub['customer_id']=formatted_values

In [161]:
order_data_sub=order_data_sub.dropna()
order_data_sub.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8000 entries, 0 to 7999
Data columns (total 8 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   order_id     8000 non-null   int64
 1   customer_id  8000 non-null   object
 2   order_date   8000 non-null   datetime64[ns]
 3   amount       8000 non-null   float64
 4   currency     8000 non-null   object
 5   status       8000 non-null   object
 6   device       8000 non-null   object
 7   country      8000 non-null   object
dtypes: datetime64[ns](1), float64(1), int64(1), object(5)
memory usage: 500.1+ KB

In [162]:
order_data_sub.head()

,order_id,customer_id,order_date,amount,currency,status,device,country
0,0,C4160,2023-08-12,-264.571496,USD,completed,desktop,US
1,1,C2075,2023-10-15,220.348791,USD,refunded,mobile,US
2,2,C285,2023-03-10,-92.077224,USD,completed,mobile,UK
3,3,C4934,2023-04-26,-177.631072,USD,refunded,desktop,US
4,4,C4927,2023-09-10,161.252214,USD,completed,mobile,UK

In [163]:
#since the customer_id should be 'C' + int value...should be no '_' in between....
order_data_sub['customer_id']=order_data_sub['customer_id'].replace('_', '',regex=True)

In [164]:
order_data_sub['customer_id'].value_counts()

customer_id
C5540    7
C4355    7
C2064    7
C4229    7
C3689    7
        ..
C2349    1
C63      1
C2531    1
C4248    1
C4722    1
Name: count, Length: 4257, dtype: int64

In [165]:
order_data_sub.duplicated().sum()

np.int64(0)

**Working on the sessions dataset**

In [166]:
sessions_data=pd.read_csv('sessions.csv')

In [167]:
sessions_data_sub=sessions_data.copy()

In [168]:
sessions_data_sub.head()

   session_id customer_id     event            timestamp
0           0        C100     click  2022-03-07 03:54:35
1           1        C100  purchase  2023-05-10 03:14:39
2           2        C100      view  2023-10-17 18:03:47
3           3        C100  purchase  2022-11-01 21:54:19
4           4        C100     click  2022-11-17 08:15:17

In [169]:
sessions_data_sub.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8000 entries, 0 to 7999
Data columns (total 4 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   session_id   8000 non-null   int64
 1   customer_id  3925 non-null   object
 2   event        8000 non-null   object
 3   timestamp    8000 non-null   object
dtypes: int64(1), object(3)
memory usage: 250.1+ KB

In [170]:
#since the customer_id should be 'C' + int value...should be no '_' in between....
sessions_data['customer_id']=sessions_data['customer_id'].replace('_', '',regex=True)

In [171]:
sessions_data['customer_id'].value_counts()

customer_id
C100    3925
Name: count, dtype: int64

In [172]:
sessions_data_sub['timestamp']=pd.to_datetime(sessions_data_sub['timestamp'])

In [173]:
random_values_session=np.random.randint(1,(0.7 * len(sessions_data_sub)),size=len(sessions_data_sub))    
formatted_values_session=[f'C{i}'for i in random_values]

In [174]:
sessions_data_sub['customer_id']=formatted_values_session

In [175]:
sessions_data_sub['customer_id']=sessions_data_sub['customer_id'].fillna('C100')

In [176]:
sessions_data_sub['customer_id'].value_counts()

customer_id
C5540    7
C4355    7
C2064    7
C4229    7
C3689    7
        ..
C2349    1
C63      1
C2531    1
C4248    1
C4722    1
Name: count, Length: 4257, dtype: int64

In [177]:
sessions_data_sub.head()

   session_id customer_id     event           timestamp
0           0       C4160     click 2022-03-07 03:54:35
1           1       C2075  purchase 2023-05-10 03:14:39
2           2        C285      view 2023-10-17 18:03:47
3           3       C4934  purchase 2022-11-01 21:54:19
4           4       C4927     click 2022-11-17 08:15:17

In [178]:
sessions_data_sub.duplicated().sum()

np.int64(0)

In [179]:
customer_data_sub.shape

(8000, 5)

In [180]:
order_data_sub.shape

(8000, 8)

In [181]:
sessions_data_sub.shape

(8000, 4)

In [182]:
# exporting the files after cleaning them
customer_data_sub.to_csv('cleaned_customers.csv')
order_data_sub.to_csv('cleaned_orders.csv')
sessions_data_sub.to_csv('cleaned_session.csv')

**End!!**